import { CompositeScreenProps, NavigatorScreenParams } from "@react-navigation/native";
import { BottomTabScreenProps } from "@react-navigation/bottom-tabs";
import { NativeStackScreenProps } from "@react-navigation/native-stack";
import { BroadcastList } from "../types";

export type AuthStackParamList = {
  Login: undefined;
  Register: undefined;
  VerifyOtp: {
    phone: string;
    displayName: string;
    username: string;
    password: string;
  };
  TwoFactorLogin: {
    pendingToken: string;
    hint: string | null;
  };
  ForgotPassword: undefined;
};

export type MainTabParamList = {
  Chats: undefined;
  Contacts: undefined;
  Discover: undefined;
  Profile: undefined;
};

export type RootStackParamList = {
  MainTabs: NavigatorScreenParams<MainTabParamList> | undefined;
  ChatRoom: { conversationId: string; title: string; highlightMessageId?: string };
  NewChat: undefined;
  NewGroup: undefined;
  NewChannel: undefined;
  AddContact: undefined;
  GroupInfo: { conversationId: string };
  AddGroupMember: { conversationId: string };
  JoinGroup: undefined;
  JoinRequests: { conversationId: string };
  GroupAuditLog: { conversationId: string };
  BannedUsers: { conversationId: string };
  CommonGroups: { userId: string };
  MutualContacts: { userId: string };
  UserProfile: { userId: string };
  EncryptionKey: { userId: string; displayName: string };
  ForwardMessage: { conversationId: string; messageIds: string[] };
  ShareContact: { conversationId: string };
  SharedMedia: { conversationId: string };
  ScheduledMessages: { conversationId: string };
  PinnedMessages: { conversationId: string; title: string };
  StarredMessages: undefined;
  Mentions: undefined;
  Reminders: undefined;
  ArchivedChats: undefined;
  ChatFolders: undefined;
  EditChatFolder: { folderId: string };
  BroadcastLists: undefined;
  EditBroadcastList: { list?: BroadcastList };
  ChatWallpaper: { conversationId: string };
  BlockedUsers: undefined;
  Birthdays: undefined;
  ChangePassword: undefined;
  ChangePhone: undefined;
  PrivacySettings: undefined;
  LastSeenExceptions: undefined;
  AppLockSettings: undefined;
  TwoFactorSettings: undefined;
  ActiveSessions: undefined;
  ChatTextSize: undefined;
  StorageUsage: undefined;
  AccountDataExport: undefined;
  MyActivity: undefined;
  QuickReplies: undefined;
  NotificationSettings: undefined;
  About: undefined;
  ThemeSettings: undefined;
  Stories: undefined;
  StoryViewer: { userId: string };
  QRCode: undefined;
  DeviceKeys: undefined;
  Call: { userId: string; displayName: string; avatarUrl: string | null; callType: "audio" | "video"; isIncoming: boolean };
  Wallet: undefined;
  SendPayment: undefined;
  MiniApps: undefined;
  MiniAppView: { id: string; name: string; url: string };
  CallHistory: undefined;
  CreateMiniApp: undefined;
  Feed: undefined;
  CreatePost: undefined;
  PostComments: { postId: string };
  Marketplace: undefined;
  StoreView: { storeId: string };
  CreateStore: undefined;
  MyStores: undefined;
  ProductView: { productId: string; storeId: string };
  MyOrders: undefined;
  AddProduct: { storeId: string };
  Discover: undefined;
  SendRedPacket: undefined;
  ClaimRedPacket: { packetId?: string };
  UserPosts: { userId: string };
  AdminDashboard: undefined;
  AdminUsers: undefined;
  AdminReports: undefined;
  StickerStore: undefined;
  StickerPackView: { packId: string };
  ChannelStats: { conversationId: string };
  StoryHighlights: { userId: string };
  QRPayment: undefined;
  QRPaymentScan: undefined;
  NearbyPeople: undefined;
  BotStore: undefined;
  BotDetail: { botId: string };
  CreateBot: undefined;
  ReelsFeed: undefined;
  CreateReel: undefined;
  FileSecurity: undefined;
  ForumTopics: { conversationId: string };
  VoiceRooms: undefined;
  VoiceRoomView: { roomId: string };
  LiveStreams: undefined;
  LiveStreamView: { streamId: string };
  ThemeStore: undefined;
  CreateTheme: undefined;
  Communities: undefined;
  CommunityView: { communityId: string };
  CreateCommunity: undefined;
  Events: undefined;
  ConversationEvents: { conversationId: string };
  GlobalSearch: undefined;
  ChannelSubscriptions: { conversationId: string };
  MySubscriptions: undefined;
  Bookmarks: undefined;
  Notes: undefined;
  ChatExports: undefined;
  MusicPlayer: undefined;
  GameCenter: undefined;
  GameView: { gameId: string; url: string; title: string };
  CloudStorage: undefined;
  Referrals: undefined;
  BusinessProfile: undefined;
  AutoReplySettings: undefined;
  Badges: undefined;
  Gifts: undefined;
  GreetingCards: undefined;
  HashtagPosts: { tag: string };
};

export type MainTabScreenProps<T extends keyof MainTabParamList> = CompositeScreenProps<
  BottomTabScreenProps<MainTabParamList, T>,
  NativeStackScreenProps<RootStackParamList>
>;
